version: '3.8'

services:
  front-end:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Exponha a porta 3000 do container na porta 3000 do host
    volumes:
      - .:/app # Monta o diretório atual no container para desenvolvimento
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
